FROM node:20-alpine

# Install git for devcontainers
RUN apk add --no-cache git

ENV NODE_ENV=production

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --non-interactive

COPY . .

RUN yarn build

EXPOSE 8080

CMD ["yarn", "start"] 