// AUTH ERRORS
export const AUTH_GUARD_TOKEN_EXPIRED = 'AUTH_GUARD_TOKEN_EXPIRED';
export const AUTH_GUARD_PARSING_ERROR = 'AUTH_GUARD_PARSING_ERROR';
export const AUTH_GUARD_MISSING_HEADER = 'AUTH_GUARD_MISSING_HEADER';
export const AUTH_GUARD_USER_NOT_FOUND = 'AUTH_GUARD_USER_NOT_FOUND';

// ERROR LOGS
export const UPDATE_FIREBASE_USER_EMAIL_ALREADY_EXISTS =
  'UPDATE_FIREBASE_USER_EMAIL_ALREADY_EXISTS';
