// Includes known/expected firebase errors from user inputs
// These errors are returned to the user and display appropriate error messages
// However these errors are ignored from rollbar and error logging
export enum FIREBASE_ERRORS {
  CREATE_USER_FIREBASE_ERROR = 'CREATE_USER_FIREBASE_ERROR',
  CREATE_USER_INVALID_EMAIL = 'CREATE_USER_INVALID_EMAIL',
  CREATE_USER_WEAK_PASSWORD = 'CREATE_USER_WEAK_PASSWORD',
  CREATE_USER_ALREADY_EXISTS = 'CREATE_USER_ALREADY_EXISTS',
  ID_TOKEN_EXPIRED = 'ID_TOKEN_EXPIRED',
  UPDATE_USER_INVALID_EMAIL = 'UPDATE_USER_INVALID_EMAIL',
  UPDATE_USER_WEAK_PASSWORD = 'UPDATE_USER_WEAK_PASSWORD',
  UPDATE_USER_ALREADY_EXISTS = 'UPDATE_USER_ALREADY_EXISTS',
  UPDATE_USER_FIREBASE_ERROR = 'UPDATE_USER_FIREBASE_ERROR',
}

export enum AUTH_GUARD_ERRORS {
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  PARSING_ERROR = 'PARSING_ERROR',
  MISSING_HEADER = 'MISSING_HEADER',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
