export enum FIREBASE_EVENTS {
  UPDATE_FIREBASE_USER_EMAIL = 'UPDATE_FIREBASE_USER_EMAIL',
  UPDATE_FIREBASE_EMAIL_ALREADY_UPDATED = 'UPDATE_FIREBASE_EMAIL_ALREADY_UPDATED',
}

export enum USER_SERVICE_EVENTS {
  USER_UPDATED = 'USER_UPDATED',
}
