export enum EVENT_NAME {
  CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
  CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED',
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  GROUNDING_EXERCISE_STARTED = 'GROUNDING_EXERCISE_STARTED',
}

export interface EventLogMetadata {
  title?: string;
}
