name: New Relic Release Tracking

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  newrelic:
    runs-on: ubuntu-24.04
    name: New Relic Release Tracking
    steps:
      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "COMMIT_REF=${{ github.ref_name }}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.5.1
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          region: 'EU'
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: '${{ env.COMMIT_REF }}'
          user: '${{ github.actor }}'
